#!/bin/bash
#coded by Fadester & Turksat46
#v1.0


#colors
green='\033[1;32m'
red='\e[1;91m'
yellow='\e[0m\e[1;93m'
lightgreen='\033[1;32m'
farblos='\e[0m'
BlueF='\e[1;34m'
cyan='\e[0;36m'
lightcyan='\033[1;36m'
lightred='\e[101m'
blink='\e[5m'
magenta='\e[35m'
Blue='\033[0;34m'
grey='\033[0;37m'

dir=$(pwd)

if [[ ! -d output ]]; then
	mkdir output
fi

clear

trap ctrl_c INT
ctrl_c() {
echo ""
echo -e "$lightcyan[$green""1$lightcyan]$Blue Menu $farblos "
echo -e "$lightcyan[$green""2$lightcyan]$Blue Exit $farblos "
echo ""
read -p $'\033[1;36m[\033[1;32m+\033[1;36m]\033[0;34m Option: \e[0m' option
if [[ $option == "1" ]]; then
	echo ""
	echo -e "$lightcyan[$green+$lightcyan]$Blue Go to Menu... $farblos "
	sleep 1
	banner 
	menu
elif [[ $option == "2" ]]; then
	echo -e "$lightcyan[$red!$lightcyan]$Blue Exiting..."
	sleep 1
	exit
else
	echo ""
	echo -e "$lightcyan[$red!$lightcyan]$Blue Invalid options! "
	ctrl_c
fi
}

banner() {
clear 
echo ""
echo -e " $green  ██░ ██  ▄▄▄       ▄████▄   ██ ▄█▀  ██████ ▄▄▄█████▓ ▄▄▄        $farblos "
echo -e " $green ▓██░ ██▒▒████▄    ▒██▀ ▀█   ██▄█▒ ▒██    ▒ ▓  ██▒ ▓▒▒████▄      $farblos "
echo -e " $green ▒██▀▀██░▒██  ▀█▄  ▒▓█    ▄ ▓███▄░ ░ ▓██▄   ▒ ▓██░ ▒░▒██  ▀█▄    $farblos "
echo -e " $green ░▓█ ░██ ░██▄▄▄▄██ ▒▓▓▄ ▄██▒▓██ █▄   ▒   ██▒░ ▓██▓ ░ ░██▄▄▄▄██   $farblos "
echo -e " $green ░▓█▒░██▓ ▓█   ▓██▒▒ ▓███▀ ░▒██▒ █▄▒██████▒▒  ▒██▒ ░  ▓█   ▓██▒  $farblos "
echo -e " $green  ▒ ░░▒░▒ ▒▒   ▓▒█░░ ░▒ ▒  ░▒ ▒▒ ▓▒▒ ▒▓▒ ▒ ░  ▒ ░░    ▒▒   ▓▒█░  $farblos "
echo -e " $green  ▒ ░▒░ ░  ▒   ▒▒ ░  ░  ▒   ░ ░▒ ▒░░ ░▒  ░ ░    ░      ▒   ▒▒ ░  $farblos "
echo -e " $green  ░  ░░ ░  ░   ▒   ░        ░ ░░ ░ ░  ░  ░    ░        ░   ▒     $farblos "
echo -e " $green  ░  ░  ░      ░  ░░ ░      ░  ░         ░                 ░     $farblos "
echo "" 
echo -e "$cyan    << -- -- ++$green Coded by Fadester & Turksat46$cyan ++ -- -- >> $farblos "
echo -e "$cyan    << -- -- ++$green              v1.0            $cyan ++ -- -- >> $farblos "

}

download_pic() {

sleep 1
bash tools/profilepic.sh
sleep 1
menu

}

follower() {

sleep 1
bash tools/follower.sh
sleep 1
menu

}

login_watcher() {
echo ""
echo -e " $yellow    __             _         __    __      _       _                $farblos "
echo -e " $yellow   / /  ___   __ _(_)_ __   / / /\ \ \__ _| |_ ___| |__   ___ ____  $farblos " 
echo -e " $yellow  / /  / _ \ / _  | |  _ \  \ \/  \/ / _  | __/ __|  _ \ / _ \  __| $farblos "
echo -e " $yellow / /__| (_) | (_| | | | | |  \  /\  / (_| | || (__| | | |  __/ |    $farblos "
echo -e " $yellow \____/\___/ \__, |_|_| |_|   \/  \/ \__,_|\__\___|_| |_|\___|_|    $farblos "
echo -e " $yellow             |___/                                                  $farblos "
echo -e "  $grey                           ......                        $farblos "
echo -e "  $grey                   .:+sydmmmmmmmmmmdhs+:.                $farblos "
echo -e "  $grey               .+ydmmmmy+-      .:odmmmmmds/             $farblos "
echo -e "  $grey            :sdmmmmmd+              -ymmmmmmmy/          $farblos "
echo -e "  $grey         -smmmmmmmms      :+oso+-     :dmmmmmmmmo.       $farblos " 
echo -e "  $grey       +dmmmmmmmmmy     +mmmmmmmmd:    -mmmmmmmmmmy-     $farblos " 
echo -e "  $grey     ommmmmmmmmmmm.    smmmmmmmmmmm:    smmmmmmmmmmms.   $farblos " 
echo -e "  $grey    hmmmmmmmmmmmmm     dmmmmmmmmmmms    +mmmmmmmmmmmmd.  $farblos " 
echo -e "  $grey     /hmmmmmmmmmmm-    ommmmmmmmmmm-    ymmmmmmmmmmmo    $farblos " 
echo -e "  $grey       :ymmmmmmmmmh     /dmmmmmmmy-    /mmmmmmmmmd+      $farblos " 
echo -e "  $grey         .+dmmmmmmmh.     ./+++:      +mmmmmmmmy:        $farblos " 
echo -e "  $grey            -ohmmmmmms-             /dmmmmmmy/           $farblos " 
echo -e "  $grey                /shmmmmds+:-...-/oymmmmmho:              $farblos " 
echo -e "  $grey                    -/+syhdmmmmddhys+:.                  $farblos "


	echo ""
	echo -e "$lightcyan[$green+$lightcyan]$Blue starting setup... $farblos"
	sleep 1.5
	python3 tools/setup.py > /dev/null 2>&1
	echo ""
	sleep 1

	python3 tools/LoginWatcher.py
	sleep 1

}

bruteforcer() {

sleep 1
bash tools/bruteforcer.sh
sleep 1
menu

}

pwfound(){

echo -e "$lightcyan[$green*$lightcyan]$Blue Password found$red! $farblos "
echo -e "$lightcyan[$green+$lightcyan]$Blue Username: $user $farblos "
echo -e "$lightcyan[$green+$lightcyan]$Blue Password: $pass $farblos "

menu

}

menu() {
banner 
echo ""
echo -e "$lightcyan[$green""1$lightcyan]$Blue Download profilepicture $farblos "
echo -e "$lightcyan[$green""2$lightcyan]$Blue Follower generator $farblos "
echo -e "$lightcyan[$green""3$lightcyan]$Blue Login watcher $farblos "
echo -e "$lightcyan[$green""4$lightcyan]$Blue Bruteforce Insta Acc $farblos "
echo ""
read -p $'\033[1;36m[\033[1;32m::\033[1;36m]\033[0;34m Choose an option: \e[0m' eingabe
if [[ $eingabe == "1" ]]; then
	download_pic
elif [[ $eingabe == "2" ]]; then
	follower
elif [[ $eingabe == "3" ]]; then
	login_watcher
elif [[ $eingabe == "4" ]]; then
	bruteforcer
fi
}

menu
